USE ROLE ACCOUNTADMIN;
CREATE SCHEMA IF NOT EXISTS DEMO_DB.ANALYTICS;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE SYSADMIN;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEMO_DB.ANALYTICS TO ROLE SYSADMIN;

GRANT CREATE TABLE, CREATE VIEW
ON FUTURE SCHEMAS IN DATABASE DEMO_DB
TO ROLE SYSADMIN;

GRANT USAGE, OPERATE
ON WAREHOUSE COMPUTE_WH
TO ROLE SYSADMIN;

GRANT ROLE SYSADMIN TO USER VIVEKWT;

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA RAW;

CREATE DATABASE DEMO_DB;
USE DATABASE DEMO_DB;

CREATE SCHEMA PUBLIC;

CREATE TABLE RAW_ORDERS (
    ORDER_ID INT,
    CUSTOMER STRING,
    AMOUNT FLOAT,
    EVENT_TIME TIMESTAMP
);

DESC TABLE RAW_ORDERS;

USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

SELECT * 
FROM RAW_ORDERS
ORDER BY EVENT_TIME DESC;

SELECT COUNT(*) FROM RAW_ORDERS;

--dbt run
---Then query:
SELECT * FROM DEMO_DB.PUBLIC.FCT_ORDERS;


USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

SELECT * FROM RAW_ORDERS ORDER BY EVENT_TIME DESC;


SELECT
  query_text,
  execution_status,
  error_message,
  start_time
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE query_text ILIKE '%RAW_ORDERS%'
ORDER BY start_time DESC;


-- for dbt
USE DATABASE DEMO_DB;
USE SCHEMA ANALYTICS;

SHOW TABLES;

SELECT COUNT(*) FROM DEMO_DB.ANALYTICS.STG_ORDERS;
SELECT COUNT(*) FROM DEMO_DB.ANALYTICS.FCT_ORDERS;

SELECT * FROM FCT_ORDERS LIMIT 10;


-- validate raw leel
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

SELECT COUNT(*) FROM RAW_ORDERS;
SELECT * FROM RAW_ORDERS ORDER BY EVENT_TIME DESC LIMIT 10;

--validat dbt
USE DATABASE DEMO_DB;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) FROM STG_ORDERS;
SELECT COUNT(*) FROM FCT_ORDERS;

SELECT * FROM FCT_ORDERS ORDER BY EVENT_TIME DESC LIMIT 10;

DESCRIBE TABLE DEMO_DB.ANALYTICS.FCT_ORDERS;

SELECT *
FROM DEMO_DB.ANALYTICS.FCT_ORDERS
ORDER BY TOTAL_AMOUNT DESC;

SELECT *
FROM DEMO_DB.ANALYTICS.FCT_ORDERS
ORDER BY TOTAL_ORDERS DESC;



